version: '3'

services:
  alt-sch-go:
    build: . #search for Dockerfile
    container_name: alt_sch_compose
    volumes:
      - .:/go/src/go-docker
    ports:
      - "8001:8080"
    networks:
      - alt_sch
networks:
  alt_sch:
    external: true